main/urls.py
from django.urls import path
from .views import index, about, contact, about_project


app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("about/", about, name='about'),
    path('kontakt/', contact, name='contact'),
    path("projekt/", about_project, name="about_project")
]

players/urls.py
from django.urls import path
from .views import players, players_add, player_profile, player_profile_biling, player_profile_activity


app_name = "players"

urlpatterns = [
    path("", players, name="players_list"),
    path("dodaj", players_add, name="players_add"),
    path("profil/<int:player_id>", player_profile, name="player_profile"),
    path("profil/<int:player_id>/biling", player_profile_biling, name="player_profile_biling"),
    path("profil/<int:player_id>/activity", player_profile_activity, name="player_profile_activity"),
]

tiny_bjj_club/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("zawodnicy/", include('players.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('/images/favicon.svg'))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

players/models.py
from django.db import models


# Create your models here.


class Player(models.Model):

    class Belts(models.TextChoices):
        WHITE = "Biały", "Biały"
        BLUE = "Niebieski", "Niebieski"
        PURPLE = "Purpurowy", "Purpurowy"
        BROWN = "Brązowy", "Brązowy"
        BLACK = "Czarny", "Czarny"

    class Stripes(models.TextChoices):
        ZERO = "0", "0"
        ONE = "1", "1"
        TWO = "2", "2"
        THREE = "3", "3"
        FOUR = "4", "4"

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    belt = models.CharField(max_length=30, choices=Belts.choices, default=Belts.WHITE)
    stripe = models.CharField(max_length=1, choices=Stripes.choices, default=Stripes.ZERO)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f"{self.id}. {self.first_name} {self.last_name}"


class PersonalInfo(models.Model):

    class Gender(models.TextChoices):
        Male = "Mężczyzna", "Mężczyzna"
        Female = "Kobieta", "Kobieta"

    user = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
    gender = models.CharField(max_length=10, choices=Gender.choices, default=Gender.Male, blank=True)
    birth_date = models.DateField(blank=True, null=True)
    first_training = models.DateField(blank=True, null=True)
    last_training = models.DateField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    email = models.EmailField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)


class MembershipFee(models.Model):

    class SubscriptionType(models.TextChoices):
        ONE = "1 Wejście", "1 Wejście"
        FOUR = "4 Wejścia", "4 Wejścia"
        EIGHT = "8 Wejść", "8 Wejść"
        FIFTEEN = "15 Wejść", "15 Wejść"
        OPEN = "OPEN", "OPEN"
        KIDS = "Dzieci i młodzież", "Dzieci i młodzież"

    user = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
    active = models.BooleanField(default=False)
    subscription_type = models.CharField(max_length=30, choices=SubscriptionType.choices, default=SubscriptionType.ONE,
                                         blank=True)
    recent_left_entries = models.PositiveIntegerField(default=0)
    sub_month = models.DateField(null=True, blank=True)


class Stat(models.Model):

    user = models.OneToOneField(Player, on_delete=models.CASCADE, primary_key=True)
    total_entries = models.PositiveIntegerField(default=0)

main/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {"message": ""}
    return render(request, "index.html", context)


def about(request):
    context = {}
    return render(request, "about.html", context)


def contact(request):
    context = {}
    return render(request, "contact.html", context)


def about_project(request):
    context = {}
    return render(request, "about_project.html", context)

players/views.py
from django.shortcuts import render
from .models import Player
from django.core.paginator import Paginator
from datetime import datetime


# Create your views here.

# TO DO:  rearange local and global variables in players method (keep pagination with players list/search funcionality)
query_players = None


def players(request):

    global query_players
    players = query_players
    query_on = request.GET.get('page')

    # Case for restart list with search button/field
    if request.method == "POST":
        get_query_item = request.POST.get("searchbar").capitalize()
        if get_query_item == "" or get_query_item == " ":
            query_players = None

    # Case for entering list or restart (show all entries)
    if players is None or query_on is None:
        query_players = Player.objects.all()
        players = Player.objects.all()

    pagination_div = 20

    # Basic cases for query results
    if request.method == "POST":
        # Bad idea but working for some cases (fix it out later)
        first_names = []
        last_names = []
        players = Player.objects.all()
        for i in players:
            first_names.append(i.first_name)
            last_names.append(i.last_name)

        search_bar = request.POST.get("searchbar").capitalize()

        if search_bar in ['Biały', "Niebieski", "Purpurowy", "Brązowy", "Czarny"]:
            players = players.filter(belt=search_bar)
            query_players = players

        elif search_bar in first_names:
            players = players.filter(first_name=search_bar)
            query_players = players

        elif search_bar in last_names:
            players = players.filter(last_name=search_bar)
            query_players = players

        # Case for zero output search
        elif search_bar != "":
            players = players.filter(first_name=search_bar)
            query_players = players

    players = Paginator(players, pagination_div)
    current_page = request.GET.get('page')
    players = players.get_page(current_page)

    context = {"players": players,
               # "query": query_param
               }

    return render(request, "players_list.html", context)


def players_add(request):
    mess = ""
    time_now = datetime.now()
    status = None

    if request.method == "POST":
        first_name = request.POST.get("first_name").capitalize()
        last_name = request.POST.get("last_name").capitalize()

        if first_name != "" and last_name != "":
            belt = request.POST.get("belt")
            stripe = request.POST.get("stripe")
            gender = request.POST.get("gender")
            mess = f"{first_name} {last_name}"
            status = "added"

            player = Player(first_name=first_name,
                            last_name=last_name,
                            belt=belt,
                            stripe=stripe,
                            gender=gender,
                            )
            player.save()

    context = {"message": mess,
               "status": status,
               "time_now": time_now,
               }
    return render(request, "players_add.html", context)


def player_profile(request, player_id):
    player = Player.objects.get(pk=player_id)

    if request.method == "POST":
        first_name = request.POST.get("first_name").capitalize()
        last_name = request.POST.get("last_name").capitalize()
        gender = request.POST.get("gender")

        player.first_name = first_name
        player.last_name = last_name
        player.gender = gender

        player.save()

    context = {"player": player}
    return render(request, "player_profile.html", context)


def player_profile_biling(request, player_id):
    player = Player.objects.get(pk=player_id)
    context = {"player": player}
    return render(request, "player_profile_biling.html", context)


def player_profile_activity(request, player_id):
    player = Player.objects.get(pk=player_id)
    context = {"player": player}
    return render(request, "player_profile_activity.html", context)

main/templates/about.html
{% extends "layout.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/players/player_list_2.css' %}" />


<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2" style="text-align: center;">
        <h1 class="display-7 fw-bold">O mnie</h1>
        <p style="margin-top: 55px; font-size: 22px;"><b>Tomasz Męczkowski</b></p>
        <p style="font-size: 18px;">Początkujący Python backend developer</p>


<!--        <img src="/static/images/github.svg" alt="gitHub icon" style="height: 40px;">-->
        <img src="{% static 'images/github.svg' %}" alt="github icon" style="height: 40px;">
        <a class="link_custom" href="https://github.com/TomaszMeczkowski" style="width: 120px;" target="_blank">GitHub</a>

        <h2 style="margin-top: 100px;">Python</h2>
        <h5>W tym obsługa bibliotek:</h5>
        <p>Numpy, Pandas, Matplotlib</p>

        <br>
        <h5>Wykorzystywane Framework-i:</h5>
        <p>Flask, Django</p>

        <h2 style="margin-top: 100px;">Bazy Danych</h2>
        <h5>Relacyjne:</h5>
        <p>MySQL, SQLite3</p>

        <br>
        <h5>Nierelacyjne</h5>
        <p>....</p>

        <h2 style="margin-top: 100px;">IDE</h2>
        <p>Pycharm community edition oraz professional, Visual Studio Code, Visual Studio</p>

        <h2 style="margin-top: 100px;">Frontend</h2>
        <p>HTML5, CSS, JS, Bootstrap</p>

        <h2 style="margin-top: 100px;">Edukacja / Kursy</h2>
        <p>2022: Pywww, Dokodu, Kurs dot. Django</p>
        <p>2022: Comarch, Bootcamp Junior Python Developer</p>
        <p>2022: FreeCodeCamp, Scientific Computing with Python </p>
        <p>2022: HardCoder - Programowanie w jeżyku Python w zakresie podstawowym</p>
        <P>2021-2022: Asysten Projektanta Mostowego w Gdańskim biurze projektowym</P>
        <p>2019-2022: Politechnia Gdańska, kierunek: Budownictwo</p>
        <p>2013-2016: Liceum Ogólno kształcące, profil matematyczno-fizyczny</p>



    </div>
</div>

{% endblock %}

main/templates/about_project.html
{% extends "layout.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/players/player_list_2.css' %}" />


<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-2">
        <h1>Opis Projektu</h1>
        <p class="lead">Pierwszy projekt aplikacji webowej z wykorzystaniem framework-a <b>Django</b>, wykorzystując technologie:</p>
        <ul>
            <li>Python 3.x </li>
            <li>HTML 5</li>
            <li>CSS 3</li>
            <li>JavaScript</li>
            <li>Bootstrap 5.2.3</li>
        </ul>
        <br />

        <h2><b>Założenia</b></h2>
        <ul>
            <li>Aplikacja organizująca pracę klubu sportowego zajmującego się Brazylijskim Jiu Jitsu (BJJ)</li>
            <li>Obsługa klienta: Sprzedaż oraz weryfikacja karnetów</li>
            <li>Wydawanie kluczyków do szafek</li>
            <li>Zbieranie statystyk o klientach</li>
            <li>Sprzedaż rzeczy nie związanych z główną działalnością klubu (napoje, koszulki itd.)</li>
            <li>Różne poziomy dostępu (recepcja, trenerzy)</li>

        </ul>

        <br>

        <h2><b>Aktualne funkcjonalności</b></h2>
        <ul>
            <li>Start projektu: 29.12.2022</li>
            <li>Wyświetlanie listy zawodników</li>
            <li>Dodawanie zawodników</li>
            <li>Przeszukiwanie listy zawodników</li>
            <li>Szczegółowe profile zawonidków</li>
            <li>Wyświetlanie statystyk zawodników</li>
            <li>Wykresy aktywności użytkowników</li>
        </ul>

        <br>

        <h2><b>Planowane funkcjonalności/pracę </b></h2>
        <ul>
            <li><b>Obsługa klienta</b></li>
            <ul>
                <li>Obsługa karnetów</li>
                <li>Sprzedaż innych produktów</li>
                <li>Sprzedaż karnetów - powiadomienia</li>
                <li>Sprzedaż karnetów - wiele karnetów (zniżki rodzinne itd)</li>
            </ul>

            <br>

            <li><b>Baza Danych</b></li>
            <ul>
                <li>Normalizacja bazy danych</li>
            </ul>

            <br>

            <li><b>Statystyki</b></li>
            <ul>
                <li>Aktywność osób trenujących</li>
                <li>Eksport excela z danymi statystycznymi</li>
                <li>Eskport JSON, txt, csv</li>
            </ul>

            <br>

            <li><b>FrontEnd</b></li>
            <ul>
                <li>Pasek nawigacji z boku do konkretnych rozdziałów tej strony</li>
                <li>Okno modalne mówiące o zalogowaniu i wylogowaniu: Zmodyfikować żeby było bardziej atrkcyjne dla użytkownika</li>
                <li>Rozbudować profil użytkownika</li>
                <li>Menu w bazie, obsłudze itd -> podświetlony przycisk obecnie wybranej opcji/strony</li>
                <li>Rozsunąć Okna menu na górze oraz dodać opcje drop down-ów np. do Obsługi klienta, bazy, statystyk itd</li>
                <li>Rozbudować o drop downy tą stronę oraz rozbudować stronę O mnie -> Wizytówka</li>
                <li>Dodać bootstrap:Nested nav do całego pliku "o projekcie"</li>
            </ul>

            <br>

            <li><b>BackEnd</b></li>
            <ul>
                <li>Usprawnić modele aplikacji players</li>
                <li>Poprawić wyszukiwanie zawodników w liście</li>
                <li>Dodać wszyukiwanie po każdych wporwadzonym znaku ("dynamiczne")</li>
                <li>Dodawanie avatarów użytkowników</li>
                <li>Usprawnić pliki statyczne</li>
                <li>Poprawić plik requirements.txt</li>
            </ul>

        </ul>


        <br />
        <h3><b>Masz jakiś pomysł na rozwinięcie aplikacji ? </b></h3>
        <p>Koniecznie napisz na <a class="link_custom" href="mailto:tomasz.meczkowski@gmail.com">tomasz.meczkowski@gmail.com</a></p>
    </div>
</div>


{% endblock %}

main/templates/contact.html
{% extends "layout.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/players/player_list_2.css' %}" />

<h2>{{ title }}</h2>
<h3>{{ message }}</h3>

<address>
    Tomasz Męczkowski<br />
    Gdańsk, PL, 80-176<br />
    <a class="link_custom" href="tel:+48513135109">+48 513 135 109</a>
</address>

<address>
  <a class="link_custom" href="mailto:tomasz.meczkowski@gmail.com">tomasz.meczkowski@gmail.com</a>
</address>

{% endblock %}

main/templates/layout.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tiny BJJ Club</title>

  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.rtl.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/site.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}"/>
  <script src="{% static 'scripts/chart.js' %}"></script>
  <script src="{% static 'scripts/jquery-3.4.1.min.js' %}"></script>

</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'main:index' %}">BJJ Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:about' %}">O mnie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:contact' %}">Kontakt</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disable" aria-disabled="true" aria-current="page" href="#">Obsług klienta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'players:players_list' %}">Zawodnicy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disable" aria-disabled="true" aria-current="page" href="#">Statystyki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'main:about_project' %}">O projekcie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disable" aria-disabled="true" aria-current="page" href="#">Konto</a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </div>

    <div class="container body-content" style="margin-top: 80px;">

        {% block content %}{% endblock %}

        <hr style="margin-top: 80px;" />
        <footer>
            <p>&copy; 2022 - BJJ Club</p>
        </footer>
    </div>

    <script src="{% static 'scripts/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'scripts/Password_Visibility.js' %}"></script>

    {% block scripts %}{% endblock %}

</body>
</html>

players/templates/inner_layout.html
{% extends "layout.html" %}

{% block content %}
{% load static %}

<div class="p-5 mb-4 bg-light rounded-3" style="margin: auto; width: 99%;">
    <div class="container-fluid py-2" style="text-align: center;">
        <h2 style="margin-bottom: 50px;">Zawodnicy</h2>
        <hr style="margin-bottom: 50px;">

        <!-- Stałe boczne menu w zakładce bazy danych -->

        <div class="row">
            <div class="col-sm-2" style="margin-top: 25px;">
                <div class="row" style="margin-bottom: 5px">
                    <a href="{% url 'players:players_add' %}" class="btn btn-outline-primary">Dodaj osobę</a>
                </div>
                <div class="row" style="margin-bottom: 5px">
                    <a href="#" class="btn btn-outline-primary">Popraw dane</a>
                </div>
                <div class="row" style="margin-bottom: 5px">
                    <a href="{% url 'players:players_list' %}" class="btn btn-outline-primary">Lista</a>
                </div>
                <div class="row" style="margin-bottom: 5px">
                    <a href="#" class="btn btn-outline-primary">Usuń</a>
                </div>
            </div>

            <div class="col-sm-10">

                {% block body %}{% endblock %}
            
            </div>

        </div>
    </div>
</div>


{% endblock %}

players/templates/player_profile.html
{% extends "inner_layout.html" %}

{% block body %}
{% load extras %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/players/player_profile.css' %}" />

<div class="container-xl px-4 mt-4">
    <!-- Account page navigation-->
    <nav class="nav nav-borders">
        <a class="nav-link active ms-0" href="{% url 'players:player_profile' player.id %}">Profil</a>
        <a class="nav-link" href="{% url 'players:player_profile_biling' player.id %}">Płatności</a>
        <a class="nav-link" href="{% url 'players:player_profile_activity' player.id %}">Aktywność</a>
        <a class="nav-link" href="https://www.bootdey.com/snippets/view/bs5-profile-security-page">Bezpieczeństwo</a>
        <a class="nav-link" href="#"  target="__blank">Ankiety</a>
    </nav>

    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <!-- Profile picture card-->
            <div class="card mb-4 mb-xl-0">
                <div class="card-header">{{player.first_name}} {{player.last_name}}</div>
                <div class="card-body text-center">

                    <!-- Profile picture image-->
                    {% if player.personalinfo.gender == 'Mężczyzna'%}
                    <img class="img-account-profile rounded-circle mb-2" src="{% static 'images/players/profile_photo/male.png' %}" alt="">
                    {% else %}
                    <img class="img-account-profile rounded-circle mb-2" src="{% static 'images/players/profile_photo/female.png' %}" alt="">
                    {% endif %}

                    <!-- Profile belt image-->
                    <img src= "{% belt_png player.belt player.stripe %}" alt='' style="width: 100px; margin-left: 10px;"/>

                    <!-- Profile belt text info-->
                    <div class="small font-italic text-muted mb-2">Pas: {{player.belt}}, {{player.stripe}} belki</div>


                    <div class="small font-italic text-muted mb-4">Status zawodnika:
                        {% if player.membershipfee.active %}
                            <b style="color: green">Aktywny</b>
                        {% else %}
                            <b style="color: red">Nieaktywny</b>
                        {% endif %}
                    </div>

                    <!-- Profile picture upload button-->
                    <button class="btn btn-outline-primary" type="button">Dodaj nowe zdjęcie</button>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <!-- Account details card-->
            <div class="card mb-4">
                <div class="card-header">Szczegóły</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (first name)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="first_name">Imię</label>
                                <input class="form-control" id="first_name" name="first_name" type="text" placeholder="Enter your first name" value="{{player.first_name}}">
                            </div>
                            <!-- Form Group (last name)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="last_name">Nazwisko</label>
                                <input class="form-control" id="last_name" name="last_name" type="text" placeholder="Enter your last name" value="{{ player.last_name }}">
                            </div>
                        </div>
                        <!-- Form Row        -->
                        <div class="row gx-3 mb-3">
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputFirstVisit">Pierwszy trening</label>
                                <input class="form-control" id="inputFirstVisit" type="date" placeholder="Enter your first training" value="{{ player.personalinfo.first_training | date:'Y-m-d' }}" disabled readonly>
                            </div>
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputLastVisit">Ostatni trening</label>
                                <input class="form-control" id="inputLastVisit" type="date" placeholder="Enter your last training" value="{{ player.personalinfo.last_training | date:'Y-m-d' }}" disabled readonly>
                            </div>
                        </div>
                        <!-- Form Row-->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (phone number)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="phone_number">Numer telefonu</label>
                                <input class="form-control" id="phone_number" type="tel" placeholder="Brak" value="{{ player.personalinfo.phone_number }}" disabled readonly>
                            </div>
                            <!-- Form Group (email)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="e_mail">E-mail</label>
                                <input class="form-control" id="e_mail" type="email" name="e_mail" placeholder="Brak" value="{% email_display player.id %}" disabled readonly>
                            </div>
                        </div>
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (birthday)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="birth_day">Rok urodzenia</label>
                                <input class="form-control" id="birth_day" type="date" value="{{ player.personalinfo.birth_date | date:'Y-m-d' }}" disabled readonly>
                            </div>
                            <!-- Form Group (gender)-->
                            <div class="col-md-6">
                                <label class="small mb-1" for="gender">Płeć</label>
                                <select class="form-select" id="gender" name="gender" aria-label="Płeć" style="height: 48px; color: grey" disabled readonly>
                                    {% if player.personalinfo.gender == "Mężczyzna" %}
                                        <option selected>Mężczyzna</option>
                                        <option value="Kobieta">Kobieta</option>
                                    {% else %}
                                        <option selected>Kobieta</option>
                                        <option value="Mężczyzna">Mężczyzna</option>
                                    {% endif %}
                                </select>
                            </div>
                        </div>

                        <!-- Form Group (created/modified date)-->
                        <div class="row gx-3 mb-3">
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputCreated">Utworzono</label>
                                <input class="form-control" id="inputCreated" type="text" placeholder=""
                                       value="{{player.personalinfo.created | date:'m/d/Y  G:i:s'}}" disabled readonly>
                            </div>
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputLastChange">Ostatnia zmiana</label>
                                <input class="form-control" id="inputLastChange" type="text" placeholder=""
                                       value="{{player.personalinfo.modified | date:'m/d/Y  G:i:s'}}" disabled readonly>
                            </div>
                        </div>

                        <!-- Save changes button-->
                        <button class="btn btn-outline-primary" type="submit">Zapisz zmiany</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xl-4">
        </div>

        <div class="col-xl-8">
            <div class="card mb-4">
            <div class="card-header">Aktywność</div>
            <div class="card-body text-end">
                <p>Ilość wszystkich treningów: {{ player.stat.total_entries }}</p>
                <p>Ilość treningów w bieżącym roku: xxx</p>
                <hr>
                <canvas id="lineChart-user-001" style="aspect-ratio: 1/2">
                <script type="module">

                    import { wykres } from "/static/scripts/charts/player_activity_chart.js";

                    let chart_id = "lineChart-user-001";
                    {#const labels = {{ context['chart_id_1']['labels'] | safe }};#}
                    let labels = ["01-2022", "02-2022", "03-2022", "04-2022", "05-2022", "06-2022", "07-2022", "08-2022", "09-2022", "10-2022", "11-2022", "12-2022"];
                    let dane = [28, 32, 30, 15, 24, 39, 28, 32, 27, 15, 24, 31];
                    let title = "Ostatnie 12 miesięcy";

                    wykres(chart_id, labels, dane, title);

                </script>
                </canvas>

                <br>
                <div class="card-text text-start">
                <button class="btn btn-outline-primary" type="button" data-bs-toggle="modal" data-bs-target="#Wykres_001_Modal">Powiększ</button>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="Wykres_001_Modal" tabindex="-1" aria-labelledby="Wykres_001_Modal_Label" aria-hidden="true">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">
                            <div class="modal-body">
{#                                <canvas id="lineChart-user-001-modal" style="aspect-ratio: 1/2">#}
                                <canvas id="lineChart-user-001-modal">
                                    <script type="module">

                                        import { wykres } from "/static/scripts/charts/player_activity_chart.js";

                                        let chart_id = "lineChart-user-001-modal";
                                        {#const labels = {{ context['chart_id_1']['labels'] | safe }};#}
                                        let labels = ["01-2022", "02-2022", "03-2022", "04-2022", "05-2022", "06-2022", "07-2022", "08-2022", "09-2022", "10-2022", "11-2022", "12-2022"];
                                        let dane = [28, 32, 30, 15, 24, 39, 28, 32, 27, 15, 24, 31];
                                        let title = "Użytkownik nr {{ player.id }}";

                                        wykres(chart_id, labels, dane, title);

                                    </script>
                                </canvas>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal" style="font-size: 14px; width: 140px; ">Zamknij</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal (Koniec) -->

            </div>
            </div>
        </div>
    </div>


</div>

{% endblock %}